# Minecraft version
minecraft_version=26.3
# Fabric Loader version
loader_version=0.19.5
# Fabric API version
fabric_version=0.161.0+26.3

# Mod Properties
mod_version=0.1.0-fabric-26.3
maven_group=org.vitalplates
archives_base_name=vitalplates

# Java version (MC 26.x requires Java 25)
java_version=25
